
export const FETCH_ALL_TOPICS = 'FETCH_ALL_TOPICS'
export const FETCH_SINGLE_TOPICS = 'FETCH_SINGLE_TOPICS'
export const FETCH_SINGLE_TOPICS_PHOTOS = 'FETCH_SINGLE_TOPICS_PHOTOS'

export const FETCH_PAGINATION_PHOTO = 'FETCH_PAGINATION_PHOTO';
