
export const FETCH_ALL_TOPICS = 'FETCH_ALL_TOPICS'
export const FETCH_SINGLE_TOPICS = 'FETCH_SINGLE_TOPICS'
export const FETCH_SINGLE_TOPICS_PHOTOS = 'FETCH_SINGLE_TOPICS_PHOTOS'

export const FETCH_PAGINATION_PHOTO = 'FETCH_PAGINATION_PHOTO';

export const  USER_PROFILE = 'USER_PROFILE';
export const  USER_PHOTOS = 'USER_PHOTOS';
export const  USER_LIKED_PHOTOS = 'USER_LIKED_PHOTOS';
export const  USER_COLLECTION = 'USER_COLLECTION';


export const SEARCH_PHOTOS = 'SEARCH_PHOTOS'
export const SEARCH_USER = 'SEARCH_USER'
export const SEARCH_COLLECTIONS = 'SEARCH_COLLECTIONS'